services:
  mosquitto:
    image: eclipse-mosquitto:2.1-alpine
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    ports:
      - "1883:1883"